name: deploy review service to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: npm install
        run: npm install
      - name: serverless
        uses: serverless/github-action@v1.53.0
      - name: set serverless credentials
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy review-service
        run: serverless deploy
